# Generated by Django 6.0 on 2026-01-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansession',
            name='completed_steps',
            field=models.IntegerField(default=0),
        ),
    ]
